### ISSUE TITLE
cursor not visible with gingerbread.

### ISSUE THREAD

**Issue by mshearer123** [btate/BTAndroidWebViewSelection#10]
First off thanks for the WebView, it works brilliantly.

I have however tried it with an older phone and cannot see the cursor within the webview, nor can I see text being highlighted on selection.

Is this a known issue?  Am I doing something wrong?

Matt

**Comment by mshearer123** [comment]
in fact the keyboard doesn't show at all, I'm guessing this is the issue - http://code.google.com/p/android/issues/detail?id=7189

**Comment by btate** [comment]
None of the content I've use this with in the past has had inputs.  What operating system/phone are you on?

**Comment by mshearer123** [comment]
with android 4.1.1 I'm able to use the webview to add text and select etc.

With android 2.3  I can select text with a popup, it however doesn't show the highlighted text.  Nor does the keyboard become enabled. 

cheers for any help,

Matt

**Comment by btate** [comment]
Is anything showing up in the textselection interface's jsError method?

**Comment by mshearer123** [comment]
Hi,

sorry I found the problem was with our html.  We were trying to use the html tag contenteditable, which isn't supported until android 3. 

cheers,

Matt

**Comment by btate** [comment]
Great. Sorry for the delayed response. Been super busy lately.
