### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by WeifonLiu** [btate/BTAndroidWebViewSelection#18]
Can you please advise what this OSS is licensed under?

Thank you and Best Regards,

Wei

**Comment by btate** [comment]
The Drag and Drop library and Quick Action library, and my files are under the Apache license.
http://www.apache.org/licenses/LICENSE-2.0.  I updated my files to include the license.

The Rangy library is under MIT http://opensource.org/licenses/mit-license.php
