### ISSUE TITLE
Not Properly working in Android KItkat

### ISSUE THREAD

**Issue by DineshNandhagopal** [btate/BTAndroidWebViewSelection#20]
Though default action of Webview is arrested by returning True on onTouchListener, along with BTWebView Text selection , default text selection is also gets enabled.Please help to resolve this

**Comment by btate** [comment]
I think the change I just committed should cover it.  Sorry for the delay, I've been a little busy.  Give it a look and let me know if I can close this.

**Comment by DineshNandhagopal** [comment]
Hi btate, Thank you very much for your help and sorry for the delay, as it is my weekend and i were out of office.yes, now the text selection is working fine.

**Comment by ravisaini1990** [comment]
But if i made true on action up so the touch event in web page not working like video play etc ,please suggest where to change so that the default selection'll be avoided and web page videos 'll play properly.
