### ISSUE TITLE
Selection doesn't work on Samsung Galaxy Tab (GT-P1000, Android 2.2)

### ISSUE THREAD

**Issue by AlexKorovyansky** [btate/BTAndroidWebViewSelection#3]
Hi,

I've tested sample app on Samsung Galaxy Tab (GT-P1000) with stock Android 2.2. Selection doesn't work.
Any ideas/fixes?

Thanks,
Alex

**Comment by btate** [comment]
I thought I had tested on that device.  I'll have to take a look at it tomorrow and I'll get back to you.

**Comment by coder4567** [comment]
I got the same problem, on android 2.2 selection doesn't work

**Comment by btate** [comment]
Since the market share for 2.2 has dipped so low, I'm not even attempting to support it anymore.  When I created this initially it worked on 2.2.  Not sure what's specific about those devices.
