### ISSUE TITLE
How would I go about having the selection follow your finger as you drag?

### ISSUE THREAD

**Issue by christopherperry** [btate/BTAndroidWebViewSelection#4]
I want to have the text actively highlight text as I drag my finger, like native text selection works.

**Comment by coder4567** [comment]
if you found a way to do it kindly let me know, I need it as well! thank u

**Comment by btate** [comment]
The way to do it would be to send the new coordinates to the javascript every time your finger moves at all. I don't currently have support for this because I think it will get choppy on slower devices.
