### ISSUE TITLE
drag webview

### ISSUE THREAD

**Issue by coder4567** [btate/BTAndroidWebViewSelection#7]
I have another problem: when I start the selection, the webview can be easily dragged horizontally even if I disabled the horizontal scrollbar.  
Any idea how can I disable the drag of the webview itself and keep the drag for the selection.
Thank you again for all your effort.

**Comment by btate** [comment]
I haven't come across that, but my guess is you'll have to test against the selection mode flag in the webview and return false for move events in the on touch handler.
